---
- name: Collect VM Provisioning Information
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Create directory with VM name
      file:
        path: "./{{ vm_name }}"
        state: directory
      
    - name: Save VM configuration
      copy:
        content: |
          vm_name: {{ vm_name }}
          cpu_count: {{ cpu_count }}
          memory_size: {{ memory_size }}
        dest: "./{{ vm_name }}/vm_config.yml"

    - name: Display saved configuration
      debug:
        msg: "Configuration saved to ./{{ vm_name }}/vm_config.yml"